KWT_index:
    path:     /
    defaults: { _controller: KWTBundle:KWT:index }

KWT_membre:
    path:     /membre
    defaults: { _controller: KWTBundle:KWT:membre }

KWT_character:
    path:     /membre/{character}
    defaults: { _controller: KWTBundle:KWT:character }

KWT_TP:
    path:     /TP
    defaults: { _controller: KWTBundle:KWT:TP }